---
abstract: "Data structure store and query genomically indexed data efficiently using SQLite's R*Tree."
author:
  - 'T. Nishimura <tnishimura@fastmail.jp>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300033, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bio-GenomeMap
requires:
  Carp: 1.26
  DBD::SQLite: 1.37
  DBI: 1.622
  Dist::Zilla::Plugin::PodWeaver: 3.101641
  Moose: 2.0604
  Storable: 0
version: 0.01
